### ISSUE TITLE
Route guides generated for tsmc65lp are invalid

### ISSUE THREAD

**Issue by tajayi** [billswartz7/UTD-BoxRouter#11]
Hi Bill,
I noticed that the route guides generated for tsmc65lp are invalid. 
Two specific issues I've faced:

**Issue 1: Bad y coordinates in the route guides**
```
orparam gcell origin {0 0}
orparam gcell rows 2
orparam gcell tracks 24
orparam gscale 2000.0
```
The Y coordinates of the gcells are wrong. In the results x grid is 9600 (good) and y grid is the whole design (bad). Every lly=0 and every ury={Height of design}. This was able to pass Bangqi's checker because every pin is in the design. Note that this is not observed with the small simple ispd testcases

**Issue 2: Tool crashes if I don't specify origin**
```
orparam gcell rows 2
orparam gcell tracks 24
orparam gscale 2000.0
```
This results in a crash
```
[CDesign::Initialize]:design [gcd]
[CDesign::Initialize]:reading flute data.
[CDesign::read_lef]:reading LEF:./objects/gcd/cadre_tech_macro.lef...done...
[CDesign::read_def]:reading DEF:./objects/gcd/gcd_cadre_placed.def...
[CDesign::create_gcell_definitions]:GCELL origin: (14.000000, 131.600000)
[CDesign::create_gcell_plane]:creating gcells...
[CDesign::create_gcell_plane]:done creating gcells...
ERROR[CDesign::init_boxes_and_layers]:GCell grid is in error:(0,0,10)
```
I also see the crash if I specify only origin and dimension. Note that this crash is not observed with the small simple ispd testcases. 

I have uploaded a debug folder for testing: t11_gr_2019-06-01_14-15.tar.gz

**Comment by billswartz7** [comment]
The problem has been verified.   The source is the problem is that the row coordinates are not being properly calculated.   Will have fix soon.

**Comment by tajayi** [comment]
thanks

**Comment by billswartz7** [comment]
The problem with the code was that the rows were assumed to be sorted.   Added row sorting to fix the base problem.   In addition, there is some confusion about the GCELL dimension command.   The original command was in real units not dbunits.   Modified the command so that the user has two choices either real or dbunits and documented the options.   You should change your command to 
orparam gcell dimension {9600 9600 0 0 dbunits}
The program now gives a warning about possible wrong units.   For example, the command
orparam gcell dimension {9600 9600 0 0} 
now gives:

WARNING[CDesign::create_gcell_definitions]:GCELL calculated xstep seems excessive.  Did you mean to use dbunits?
WARNING[CDesign::create_gcell_definitions]:GCELL calculated ystep seems excessive.  Did you mean to use dbunits?
[CDesign::create_gcell_plane]:creating gcells...
[CDesign::create_gcell_plane]:done creating gcells...
ERROR[CDesign::init_boxes_and_layers]:GCell grid is in error:(0,0,10)

The repository has been updated.

**Comment by tajayi** [comment]
validated
